In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
email=pd.read_csv(r"A:\lenovo\Desktop\datasets\Phishing_Email.csv")
email.head()

,Unnamed: 0,Email Text,Email Type
0,0,"re : 6 . 1100 , disc : uniformitarianism , re ...",Safe Email
1,1,the other side of * galicismos * * galicismo *...,Safe Email
2,2,re : equistar deal tickets are you still avail...,Safe Email
3,3,\nHello I am your hot lil horny toy.\n I am...,Phishing Email
4,4,software at incredibly low prices ( 86 % lower...,Phishing Email

In [4]:
email.drop('Unnamed: 0',axis=1,inplace=True)

In [5]:
email.head()

                                          Email Text      Email Type
0  re : 6 . 1100 , disc : uniformitarianism , re ...      Safe Email
1  the other side of * galicismos * * galicismo *...      Safe Email
2  re : equistar deal tickets are you still avail...      Safe Email
3  \nHello I am your hot lil horny toy.\n    I am...  Phishing Email
4  software at incredibly low prices ( 86 % lower...  Phishing Email

In [6]:
email.isnull().sum()

Email Text    16
Email Type     0
dtype: int64

In [7]:
email=email.dropna()

In [8]:
email.isnull().sum()

Email Text    0
Email Type    0
dtype: int64

In [9]:
email['Email Type'].value_counts()

Email Type
Safe Email        11322
Phishing Email     7312
Name: count, dtype: int64

In [10]:
import re

def clean_text(text):
    text = text.lower()
    text = re.sub(r"http\S+", "", text)
    text = re.sub(r"[^a-z\s]", "", text)
    return text

In [11]:
email["clean_text"] = email["Email Text"].astype(str).apply(clean_text)

In [12]:
email["label"] = email['Email Type'].map({
    "Safe Email": 0,
    "Phishing Email": 1
})

print(email["label"].value_counts())

label
0    11322
1     7312
Name: count, dtype: int64

In [13]:
texts = email["clean_text"].tolist()
labels = email["label"].tolist()

In [14]:
from sklearn.model_selection import train_test_split

X_train, X_temp, y_train, y_temp = train_test_split(
    texts, labels,
    test_size=0.2,
    stratify=labels,
    random_state=39
)

X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp,
    test_size=0.5,
    stratify=y_temp,
    random_state=13
)

In [15]:
X_test

['iatl  israel association for theoretical linguistics forteenth annual conference we enclose details about accommodation  travel and the schedule for iatl   to be held be held in ben gurion university  beer sheva  on june      we hope you will be able to join us  accommodation  people wishing to book accommodation should contact ariel cohen  arikc  bgumail  bgu  ac  il  asap  there are three main options   beersheva hilton  single    double    suite    all prices per night and include breakfast  the prices do not include   vat    neot midbar hotel  single    double    triple    lunch    dinner    at the red sand grill restaurant    bgu dorms  shared apartment   nis  approx    for one night  or  nis     approx  for up to a week  own apartment  suitable for a couple    nis for one night  or  nis for up to a week  travel  beersheva is well connected to both telaviv and jerusalem by fast  air conditioned egged buses  ask driver for ben gurion university stop  once you  re safely off the bus  cross the road  main entrance becomes visible immediately  drivers  turn left to ben gurion ave   which is the street running south of the university and north of a big hospital  take the second left turn  a turn without a traffic light  if you hit a light  you have driven too far   you will see two gates with barriers  pick the one on the left  this is the visitors  paid  parking  schedule  monday morning  june    conference hall       registration and coffee      greetings      invited talk  g  cinque  venice  adverbs and functional heads      s  zuckerman  groningen  no true optionality      lunch monday afternoon  june    conference hall       j  quer  utrecht  free relatives and the contribution of mood shift      i  landau  mit  on possessor raising in hebrew      a  grosu  tel aviv  carlsonian contexts are all  filters  not  plugs       coffee      d  kolliakou  newcastle  jerusalem  linkhood and the syntax of definites      s  wintner  tuebingen  definiteness agreement and inheritance in hebrew    dinner tuesday morning  june    conference hall       coffee      k  wexler  mit   j  schaeffer  beersheva   g  bol  groningen  verbal syntax and morphology in dutch normal and sli children      i  elisha  bar ilan  the minimal competence hypothesis in functional categories and child language      w  sandler  haifa   m  nespor  amsterdam  prosodic phonology in sign language      lunch tuesday afternoon  june    conference hall       s  rothstein  bar ilan  achievements and progressives      g  brugger  los angeles  time points and temporal modification      coffee      b  ritter  calgary  agreement in the semitic prefix conjugation  evidence for a nonlinear approach to person  number and gender agreement      a  sherman  santa cruz  roots and correspondence  denominal verbs in modern hebrew',
 'ferc orders on ca and rto west      forwarded by sarah novosel  corp  enron on         pm       jackie gallagher          pm to             cc  subject  ferc orders on ca and rto west attached are the ferc orders on california and rto west  as discussed on today  s power marketers conference call  they will be posted on ferc  s website shortly  at www  ferc  fed  us  attachments  rtol      pdf     order  pdf',
 'translators needed for women for women  i am posting the following message for my friends who are not on the list   would you like to use your language skills to help women survivors of the war in bosnia and croatia  women for women  a u  s  based  nonprofit sponsorship program sending letters and money each month to the region  is desperately seeking volunteer translators  we translate letters both from and to english  even if you can manage only a handful of letters each month  it would lighten the load for the few translators we have now  for more information  call our office at      and leave a message for zainab or robin  thank you   you may also send an email message to me mima  seur  voa  gov and i will forward it to  women for women  ',
 'gtv ii weekly status update louise  the gtv ii team has a weekly status meeting on mondays  yesterday  we had our first status meeting  please see below for the current status of the project  please see the attached file for the update of project timeline in microsoft project  gtv status meeting attendees  zhiyong wei  karima husain  francis lim  jeremy wong  bill fortney  nayan dattani  mike swaim  dave nommensen  russ severson  george grant  accomplishments   incorporating physcial deal positions in tds  o changes to cpr reader process have been completed  o changes for the view aggregation are   done  o changes for the position manager are in progress and are about   completed   single point of deal entry for term deals  o establishing communication between tds client  sitara server is in progress   gas daily deals  o changes to tds deal valuation are in progress  o creating gdi calc in erms is in progress   live feeds for gas daily  intra  month curves  o development of live feeds is in progress  goef has been contacted regarding how to use the features  plans for the week ending        continue the development of gtv ii phase    commence the work on gtv ii phase  inception document  issues  none  regards zhiyong',
 'check this impotence medication don  t ignore your impotence problems feeling good is around the corner  try now http    buychepmeds  com best regards  marquis pack phone       mobile       email  zndnioays  sina  com  hk s  t    p http    buychepmeds  com  emover  php',
 'original message   date mon  aug     from chad norwood  to sven  cc razorusersexamplesourceforgenet  subject razorusers re questions on miscellaneous errata and issues   on    sven wrote   in tweaking my system to try to optimize the use of razor this now from a networkconnectionetc standpoint not so much from a philosphical stance on what is or is not considered spam and who should decide it i have come across a couple issues that i hope i may be able to get some relief on       what exactly does unable to connect to honorcloudmarkcom reason operation now in progress mean  i have seen this error message some  times today between  clustered servers representing a little over  failure rate in an enterprise level i was hoping for more along the lines of maybe onetenth that    its a network error  that string is not created by  razor agents its trying to connect and having trouble   times seems abnormally high how many successful  connections were there in the same timespan today was not as bad  aptcloudmark was the server du jour and experienced about  unable to connect  reason operation now in progress out of some  bootup or roughly   better than the  before but still a bit higher than i would like i suspect it is because a previous timeout from razoragents has a process id that is being held by an open milter socket the process ids cycle the number comes up again and the error occurs as a duplicate pid occurs i will tweak my milter settings to shorten the total time to allow the socket to live per connect    related somewhat to question  is there or will there be if currently not a way of adjusting the timeout the setting for the razorcheck to await a response from the server it queries i am running this as a sendmail milter and adjusting the milter timeouts wont help if the razorcheck script times out first anyway    the timeout is hardcoded to  secs  no plans right now to make that an option  you can always edit the source  corepm in looking at corepm i find a couple possible places where that code might be is it my select  new ioselect sock my handles  selectcanread  if handles  selflog connection established my greeting  sock  sockautoflush  this is on by default as of iosocket  selfsock  sock selfconnectedto  server selfselect  select selflogserver   lengthgreeting  server greeting greeting return  if paramsdiscoveryserver unless selfparsegreetinggreeting   selfnextserver or return selferrprefixconnect return selfconnect  return   else  selflog  timed out  sec while reading from selfsip  or unless sock  sock  iosocketinetnew peeraddr  server peerport  port proto  tcp timeout    unless  sock   selflog unable to connect to serverport reason  return if paramsdiscoveryserver selfnextserver or return selferrprefixconnect return selfconnect    of course the latter reflects a differenct timeout setting altogether  one part for proxy the other for nonproxy     what are the plans for firecloudmark aptcloudmark ubikcloudmark it seems that we have all these catalogue servers yet a good portion of the time only one is available or the last discovery ends up only listing one currently honorcloudmark in the catalogelst file   the system is designed so servers can be added and  subtracted without the clients caring  if the razor  client cant connect to a server it rediscovers getting  all currently available servers and stores results locally i changed the default discovery period to every  hours in order to compensate for the recent sporadic nature of the servers availability i realize that the issue was related to syncing and server upgrades  but i might as well play it safe for a while    what would be the implicationsrequirementscaveats of hosting a catalogue server or at the minimum a caching server similar to the way mailabuseorg for example does dns zone transfers of its rbl list  i realize that this is a completely different mechanism but you get the point i am driving at here i realize that there is an issue of polluting the catalogue but perhpas there could be some way of certifying a catalogue server what type of bandwidth considerations are we looking at here it is just the signatures that are actually transferred across the pipes is it not   we are looking into releasing caching catalogue servers  for those besides us to useif i can be of help or if you have details about to participate in this portion caching or catalogueing please let me know    it really looks like there is a great potential here for a very workable tool and if i can get some of these issues addressed or can even be of some assistance all the better      sven willenberger   systems administration   delmarva online inc    thanks   chad          razorusers mailing list  razoruserslistssourceforgenet      end of razorusers digest this sfnet email is sponsored by dice  the leading online job board for hightech professionals search and apply for tech jobs today   razorusers mailing list razoruserslistssourceforgenet ',
 'fw  at our medzplace  you locate top  selling taablets at super decreased prices only  locating a better way to pur  chase prescribed remedies   at our chernist  site  you have an extensive selections on quality rxdrugs   select quick relief for discomforts like pain  severe tensions  over vveight  sleeping disorder and erectile tissue dysfunction  at our medzone  your or  der will be sent by experienced logistic companies  select easy pricing on quality items  have you checked the current weekly special already  on our site  your case will be reviewed by physicians http    n   o   gettingandfindings  com  i        original message      from  rueben  icqi  com  mailto  isaiah  lxg  com  sent  thursday  march       pm to  shawn  august  w  com   marcelo  german subject  at our shovvroom  your case profile will be checked by licensed experts for nada   eshopping helps me or  der my medicines quickly  all the items on site are sold at wonderful reduced prices  it is really a convenience to select your site for my medical needs    bonnie k  in mt with a view the warm and faithful feelings of any of my fellow  creatures  i should deserve utter contempt if i dared to suppose that true attachment of st  paul  s cathedral  six   and after another half mile of gradual ascent through large enclosures   with a  pink dome  painted on t  he top  at the brass thimbl e on her finger  at he',
 'logo  corporate identity and website design corporate image can say a lot of things about your company  contemporary rhythm of life is too dynamic  sometimes it takes oniy several seconds for your company to be remembered or to be lost among competitors  get your loqo  business stationery or website done riqht now  fast turnaround  you wili see several logo variants in three business days  satisfaction guaranteed  we provide uniimited amount of changes  you can be sure  it wili meet your needs and fit your business  fiexible discounts  logo improvement  additionai formats  bulk orders  special packages  creative design for competitive price  have a look at it right now ',
 'empty',
 'dear all if you wish to find out more about the mission in kosovo  you can find news and photos at  www  kforonline  com   take care  mark do you yahoo   get your free  yahoo  co  uk address at http    mail  yahoo  co  uk or your free  yahoo  ie address at http    mail  yahoo  ie',
 'this is a legitimate way for you to secure specials on quality medicines  i don  t know whether other people who suffer from chronic diseases have the same feeling  to recieve a refil  seems to take a greater amount of time than it should  and the prices on taablets are scary  my experience proved so  the prices on r  xdrugs are really reduced from other stores  thank you for providing this wonderful arrangement    mark j  in sd it is quick and convenient way for you to purchase rxmeds at our rxdrug  site  our company provides a wide variety of r  xdrugs at the unsurpassed prices  our professional logistic supports bring customers additional conveniences  http      n  songchorus  com  iw  inheritance had been an old bible  which she read and valued  from its pages she heard the voice of god speaking to her  and telling her to remember what was said of joseph  s brethren when persons wished to injure her  they imagined evil in their hearts  but god turned it to good  if we suffer wrongfully  if we are misunderstood or despised  we must think of him who was pure and holy  and who prayed for those who nailed him to the cross  father forgive them  for they know not what they do  the probable cause  he had been absent only two sundays  the honour of calling on mrs musgrove in the course of the morning ',
 '\n\xa0you cant predict the future but you can always prepare for it\xa0              double               your life insurance policy for \n              no extra cost              \xa0compare rates from top insurance companies around the country\nin our life and times its important to plan for your familys future while \nbeing comfortable financially choose the right life insurance policy today\xa0\nyoull be able to compare rates and get a\nfree application\nin less than a \nminute\ncompare your coverage\n              as low as\nper month\n\xa0\n              as low as              \n              per month\n\xa0\n              as low as              \n              per month\n\xa0get your\nfree\ninstant quotes compare the lowest prices then\n                  \nselect a company and apply online\n                  dont \n              miss this get your free instant quote               click for your free quote now              \xa0\nsmoker rates also available              \xa0\nmake\xa0\xa0\xa0\xa0 \n              insurance companies compete for your insurance\n\xa0\nwe have \n            eliminated the long process of finding the best rate by giving you \n            access to multiple insurance companies all at onceapply \n                now and one of our insurance brokers will get back to you within \n                 hoursclick hereif you wish to be removed from future mailings please clicking \nhere  \n\xa0\n',
 'teeth bleaching  whitening kit your dentist can whiten and bleach your teeth at a cost of        this process has been successfully utilized by dental professionals for over  years  do it yourself and save     purchase the identical kit from a  manufacturer that supplies dentists  only    us for internet consumers  shipped worldwide  visit the american dental supply  llc website at  http    www  teethwhite  com',
 'hiya   find your meds here   stanchion bizarre save over   onkprescriptionpdrugs with our on  linespharmacy you can   order name right from home  not the cheap european versions on sites offer    get it shipped same day to your door step   never have to worry about getting a doctorqto write the prescriptioncagain   save hundreds of dollars over your localipharmacy if all this sounds good to you then you need to click here for more about what we offer  we carry everything from vicodin  valum  xanax  and viagra  so go to our site to see how much we can save you today ',
 'look this is so hot that not only do you want one but you can get rich selling it to others some will use it for good and many will use it for bad either way the unit worksit is a bulb but it is not a bulb it is a secret wireless camera use professionally by cia fbi and others original cost was over  but because someone went to china to knock them off you now can buy it today for  each or  for  or  for  do the math you can earn  per unit or more and sell  in a week all people need to do is see one and they flip outhere is how it worksyou screw it into any lamp wall  or ceiling bulb socet even over the shower it could be in a dark place it dont matter put it in your bedroom and make sure your wife does not have company while you are working i am telling you man you would pay s for this toy then you take the other piece and plug it into your vcr and it is as if you were standing over the person wi\nth\n a video camera as i said some will use it for good and some will use it for bad and some will be like me and just get rich selling them all you need do is demo it and they buy it heh he even if it takes a day to sell just one you make but who says you have to charge  you can charge  and make  follow the rest of the information and check it outspecial sale thru july st                 why am i receiving this email  because you or someone using this email address has opted to receive new product information from internethitz or one of its entrusted partnersthank you for your patronage\nif this is an error please send an email to be removed\nin the subject line type remove me listx\nmail to meoffnowkbyahoocomdeathtospamdeathtospamdeathtospam\n\nthis sfnet email is sponsored by jabber  the worlds fastest growing \nrealtime communications platform dont just im build it in \n\n\nspamassassinsightings mailing list\nspamassassinsightingslistssourceforgenet\n\n',
 're  planning for your energy finance class presentation wed      ehud  i am flying back in the evening and dinner would be difficult  i shall be glad to join you for lunch  shirley  as i understand gave you my requirements for the av  my flight arrives at    a  m  i can meet you at your office in the morning and we can talk about the conference and other issues  vince  ehud i  ronn  on           am to  vkamins  enron  com cc  subject  planning for your energy finance class presentation wed      vince  good morning  further to your forthcoming visit this wed   i write to clarify last  minute details    your eta  etd  will you be available to join us for lunch and  or dinner    your av requirements  if any  should you need either  we have an overhead projector as well as laptop capability  either your laptop  or we can with advance notice reserve a laptop if you bring floppies   btw  any developments re jeff skilling  s    conference keynote  best  ehud ehud i  ronn jack s  josey professor in energy studies department of finance mccombs school of business university of texas at austin austin  tx     voice        fax        internet  eronn  mail  utexas  edu',
 'hpl nom for april     see attached file  hplno   xls   hplno   xls',

In [16]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

MAX_WORDS = 10000
MAX_LEN = 200

tokenizer = Tokenizer(num_words=MAX_WORDS, oov_token="<OOV>")
tokenizer.fit_on_texts(X_train)

X_train_seq = pad_sequences(
    tokenizer.texts_to_sequences(X_train),
    maxlen=MAX_LEN,
    padding="post"
)

X_val_seq = pad_sequences(
    tokenizer.texts_to_sequences(X_val),
    maxlen=MAX_LEN,
    padding="post"
)

X_test_seq = pad_sequences(
    tokenizer.texts_to_sequences(X_test),
    maxlen=MAX_LEN,
    padding="post"
)

WARNING:tensorflow:From a:\lenovo\Desktop\TruthScope-Flask\lp2\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [17]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout

model = Sequential([
    Embedding(MAX_WORDS, 128, input_length=MAX_LEN),
    LSTM(128, return_sequences=False),
    Dropout(0.5),
    Dense(1, activation="sigmoid")
])

model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

model.summary()

WARNING:tensorflow:From a:\lenovo\Desktop\TruthScope-Flask\lp2\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

WARNING:tensorflow:From a:\lenovo\Desktop\TruthScope-Flask\lp2\Lib\site-packages\keras\src\optimizers\__init__.py:309: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 embedding (Embedding)       (None, 200, 128)          1280000

 lstm (LSTM)                 (None, 128)               131584

 dropout (Dropout)           (None, 128)               0

 dense (Dense)               (None, 1)                 129

=================================================================
Total params: 1411713 (5.39 MB)
Trainable params: 1411713 (5.39 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [18]:
import numpy as np

X_train_seq = np.array(X_train_seq)
X_val_seq   = np.array(X_val_seq)

y_train = np.array(y_train)
y_val   = np.array(y_val)

In [19]:
from sklearn.utils.class_weight import compute_class_weight

class_weights = compute_class_weight(
    class_weight="balanced",
    classes=np.array([0, 1]),
    y=y_train
)

class_weight_dict = {
    0: class_weights[0],
    1: class_weights[1]
}

In [20]:
history = model.fit(
    X_train_seq,
    y_train,
    epochs=5,
    batch_size=32,
    validation_data=(X_val_seq, y_val),
    class_weight=class_weight_dict
)

Epoch 1/5
WARNING:tensorflow:From a:\lenovo\Desktop\TruthScope-Flask\lp2\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From a:\lenovo\Desktop\TruthScope-Flask\lp2\Lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

466/466 [==============================] - 46s 94ms/step - loss: 0.5533 - accuracy: 0.7019 - val_loss: 0.5248 - val_accuracy: 0.7123
Epoch 2/5
466/466 [==============================] - 47s 101ms/step - loss: 0.2807 - accuracy: 0.8989 - val_loss: 0.3255 - val_accuracy: 0.9023
Epoch 3/5
466/466 [==============================] - 46s 98ms/step - loss: 0.3290 - accuracy: 0.8907 - val_loss: 0.4986 - val_accuracy: 0.8170
Epoch 4/5
466/466 [==============================] - 45s 97ms/step - loss: 0.3144 - accuracy: 0.8933 - val_loss: 0.2796 - val_accuracy: 0.9136
Epoch 5/5
466/466 [==============================] - 43s 91ms/step - loss: 0.2234 - accuracy: 0.9272 - val_loss: 0.2266 - val_accuracy: 0.9163

In [21]:
model.save("new_email_lstm_model.keras")

In [22]:
import pickle

with open("new_email_lstm_tokenizer.pkl", "wb") as f:
    pickle.dump(tokenizer, f)

In [ ]:
#95.81 accuracy