In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [13]:
x=pd.read_csv(r"C:\Users\shubh\Downloads\nlp-getting-started\train.csv")
x

,id,keyword,location,text,target
0,1,NaN,NaN,Our Deeds are the Reason of this #earthquake M...,1
1,4,NaN,NaN,Forest fire near La Ronge Sask. Canada,1
2,5,NaN,NaN,All residents asked to 'shelter in place' are ...,1
3,6,NaN,NaN,"13,000 people receive #wildfires evacuation or...",1
4,7,NaN,NaN,Just got sent this photo from Ruby #Alaska as ...,1
...,...,...,...,...,...
7608,10869,NaN,NaN,Two giant cranes holding a bridge collapse int...,1
7609,10870,NaN,NaN,@aria_ahrary @TheTawniest The out of control w...,1
7610,10871,NaN,NaN,M1.94 [01:04 UTC]?5km S of Volcano Hawaii. htt...,1
7611,10872,NaN,NaN,Police investigating after an e-bike collided ...,1
7612,10873,NaN,NaN,The Latest: More Homes Razed by Northern Calif...,1

In [15]:
import warnings
warnings.filterwarnings('ignore')

In [17]:
x.drop("keyword",axis=1,inplace=True);

In [21]:
x.drop("location",axis=1,inplace=True);

In [23]:
x.drop("id",axis=1,inplace=True);

In [25]:
x.head()

                                                text  target
0  Our Deeds are the Reason of this #earthquake M...       1
1             Forest fire near La Ronge Sask. Canada       1
2  All residents asked to 'shelter in place' are ...       1
3  13,000 people receive #wildfires evacuation or...       1
4  Just got sent this photo from Ruby #Alaska as ...       1

In [31]:
x["target"].value_counts()

target
0    4342
1    3271
Name: count, dtype: int64

In [33]:
x.isnull().sum()

text      0
target    0
dtype: int64

In [9]:
x=x.dropna(subset=['keyword'])

In [11]:
x

,id,keyword,location,text,target
31,48,ablaze,Birmingham,@bbcmtd Wholesale Markets ablaze http://t.co/l...,1
32,49,ablaze,Est. September 2012 - Bristol,We always try to bring the heavy. #metal #RT h...,0
33,50,ablaze,AFRICA,#AFRICANBAZE: Breaking news:Nigeria flag set a...,1
34,52,ablaze,"Philadelphia, PA",Crying out for more! Set me ablaze,0
35,53,ablaze,"London, UK",On plus side LOOK AT THE SKY LAST NIGHT IT WAS...,0
...,...,...,...,...,...
7578,10830,wrecked,NaN,@jt_ruff23 @cameronhacker and I wrecked you both,0
7579,10831,wrecked,"Vancouver, Canada",Three days off from work and they've pretty mu...,0
7580,10832,wrecked,London,#FX #forex #trading Cramer: Iger's 3 words tha...,0
7581,10833,wrecked,Lincoln,@engineshed Great atmosphere at the British Li...,0
7582,10834,wrecked,NaN,Cramer: Iger's 3 words that wrecked Disney's s...,0

In [ ]:
x=x.dropna(subset=['keyword'])

In [7]:
x.isnull().sum()

id             0
keyword        0
location    2472
text           0
target         0
dtype: int64

In [8]:
x['location'] = x['location'].fillna('unknown')

In [9]:
x.isnull().sum()

id          0
keyword     0
location    0
text        0
target      0
dtype: int64

In [12]:
x.target.unique()

array([1, 0], dtype=int64)

In [21]:
x.drop('id',axis=1,inplace=True)
x

,keyword,location,text,target
31,ablaze,Birmingham,@bbcmtd Wholesale Markets ablaze http://t.co/l...,1
32,ablaze,Est. September 2012 - Bristol,We always try to bring the heavy. #metal #RT h...,0
33,ablaze,AFRICA,#AFRICANBAZE: Breaking news:Nigeria flag set a...,1
34,ablaze,"Philadelphia, PA",Crying out for more! Set me ablaze,0
35,ablaze,"London, UK",On plus side LOOK AT THE SKY LAST NIGHT IT WAS...,0
...,...,...,...,...
7578,wrecked,unknown,@jt_ruff23 @cameronhacker and I wrecked you both,0
7579,wrecked,"Vancouver, Canada",Three days off from work and they've pretty mu...,0
7580,wrecked,London,#FX #forex #trading Cramer: Iger's 3 words tha...,0
7581,wrecked,Lincoln,@engineshed Great atmosphere at the British Li...,0
7582,wrecked,unknown,Cramer: Iger's 3 words that wrecked Disney's s...,0

In [23]:
x.location.unique()

array(['Birmingham', 'Est. September 2012 - Bristol', 'AFRICA', ...,
       'Vancouver, Canada', 'London ', 'Lincoln'], dtype=object)

In [25]:
x['location'].value_counts()

location
unknown                2472
USA                     104
New York                 71
United States            50
London                   45
                       ...
MontrÌ©al, QuÌ©bec        1
Montreal                  1
ÌÏT: 6.4682,3.18287       1
Live4Heed??               1
Lincoln                   1
Name: count, Length: 3342, dtype: int64

In [27]:
x

,keyword,location,text,target
31,ablaze,Birmingham,@bbcmtd Wholesale Markets ablaze http://t.co/l...,1
32,ablaze,Est. September 2012 - Bristol,We always try to bring the heavy. #metal #RT h...,0
33,ablaze,AFRICA,#AFRICANBAZE: Breaking news:Nigeria flag set a...,1
34,ablaze,"Philadelphia, PA",Crying out for more! Set me ablaze,0
35,ablaze,"London, UK",On plus side LOOK AT THE SKY LAST NIGHT IT WAS...,0
...,...,...,...,...
7578,wrecked,unknown,@jt_ruff23 @cameronhacker and I wrecked you both,0
7579,wrecked,"Vancouver, Canada",Three days off from work and they've pretty mu...,0
7580,wrecked,London,#FX #forex #trading Cramer: Iger's 3 words tha...,0
7581,wrecked,Lincoln,@engineshed Great atmosphere at the British Li...,0
7582,wrecked,unknown,Cramer: Iger's 3 words that wrecked Disney's s...,0

In [35]:
ip=x.drop('target',axis=1)
ip.head()

                                                text
0  Our Deeds are the Reason of this #earthquake M...
1             Forest fire near La Ronge Sask. Canada
2  All residents asked to 'shelter in place' are ...
3  13,000 people receive #wildfires evacuation or...
4  Just got sent this photo from Ruby #Alaska as ...

In [37]:
op=x.drop(ip,axis=1)
op.head()

   target
0       1
1       1
2       1
3       1
4       1

In [33]:
from sklearn.model_selection import train_test_split
xtr,xts,ytr,yts=train_test_split(ip,op,test_size=0.2,random_state=13)

In [34]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.compose import ColumnTransformer

In [37]:
tfidf = ColumnTransformer([
    ('text_tfidf', TfidfVectorizer(max_features=3000), 'text'),
    ('keyword_tfidf', TfidfVectorizer(max_features=500), 'keyword'),
    ('location_tfidf', TfidfVectorizer(max_features=500), 'location')
])

In [39]:
X_train_vec = tfidf.fit_transform(xtr)

In [41]:
X_val_vec = tfidf.transform(xts)

In [43]:
yts

      target
4778       0
1313       0
3963       1
1861       1
1142       1
...      ...
5409       0
4406       0
945        0
6457       1
7024       1

[1511 rows x 1 columns]

In [45]:
ytr

      target
7100       0
3089       0
5574       1
4759       1
6895       0
...      ...
897        0
2821       0
105        0
6351       0
369        0

[6041 rows x 1 columns]

In [47]:
from keras.models import Sequential
from keras.layers import Dense,Dropout, BatchNormalization
from keras.optimizers import Adam
from keras.regularizers import l2

In [53]:
from keras.models import Sequential
from keras.layers import Dense, Dropout, BatchNormalization
from keras.optimizers import Adam
from keras.regularizers import l2

model = Sequential()
model.add(Dense(128, input_dim=3739, activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.3))

model.add(Dense(64, activation='relu', kernel_regularizer=l2(0.001)))
model.add(BatchNormalization())
model.add(Dropout(0.3))

model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer=Adam(learning_rate=0.0001),
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(
    X_train_vec.toarray(), ytr,
    validation_data=(X_val_vec.toarray(), yts),
    epochs=20,
    batch_size=64,
)

Epoch 1/20
95/95 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.5038 - loss: 0.9919 - val_accuracy: 0.5983 - val_loss: 0.7598
Epoch 2/20
95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.6229 - loss: 0.7980 - val_accuracy: 0.6089 - val_loss: 0.7378
Epoch 3/20
95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.7047 - loss: 0.6618 - val_accuracy: 0.6724 - val_loss: 0.7075
Epoch 4/20
95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.7694 - loss: 0.5627 - val_accuracy: 0.7478 - val_loss: 0.6649
Epoch 5/20
95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.7918 - loss: 0.5284 - val_accuracy: 0.7829 - val_loss: 0.6148
Epoch 6/20
95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8171 - loss: 0.4906 - val_accuracy: 0.7869 - val_loss: 0.5716
Epoch 7/20
95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8236 - loss: 0.4666 - val_accuracy: 0.7842 - val_loss: 0.5492
Epoch 8/20
95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8469 - loss: 0.4203 - val_accuracy: 0.7862 - val_loss: 0.5432
Epoch 9/20
95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8671 - loss: 0.3899 - val_accuracy: 0.7909 - val_loss: 0.5443
Epoch 10/20
95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.8882 - loss: 0.3602 - val_accuracy: 0.7895 - val_loss: 0.5480
Epoch 11/20
95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9091 - loss: 0.3255 - val_accuracy: 0.7909 - val_loss: 0.5499
Epoch 12/20
95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9120 - loss: 0.3125 - val_accuracy: 0.7915 - val_loss: 0.5507
Epoch 13/20
95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9149 - loss: 0.2935 - val_accuracy: 0.7915 - val_loss: 0.5553
Epoch 14/20
95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9240 - loss: 0.2747 - val_accuracy: 0.7955 - val_loss: 0.5610
Epoch 15/20
95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9324 - loss: 0.2543 - val_accuracy: 0.7962 - val_loss: 0.5651
Epoch 16/20
95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9364 - loss: 0.2507 - val_accuracy: 0.7915 - val_loss: 0.5702
Epoch 17/20
95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9424 - loss: 0.2382 - val_accuracy: 0.7955 - val_loss: 0.5766
Epoch 18/20
95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9521 - loss: 0.2161 - val_accuracy: 0.7935 - val_loss: 0.5874
Epoch 19/20
95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9605 - loss: 0.2008 - val_accuracy: 0.7942 - val_loss: 0.5938
Epoch 20/20
95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9576 - loss: 0.2041 - val_accuracy: 0.7975 - val_loss: 0.6037

In [55]:
import keras
print(keras.__version__)

3.5.0

In [57]:
model.save("best_model_80.keras")  # Correct format for Keras 3.5.0

In [61]:
import joblib

# Save to local file
joblib.dump(tfidf, "vectorizer.pkl")

['vectorizer.pkl']

In [67]:
print(type(tfidf))
print(tfidf.get_params())

<class 'sklearn.compose._column_transformer.ColumnTransformer'>
{'force_int_remainder_cols': True, 'n_jobs': None, 'remainder': 'drop', 'sparse_threshold': 0.3, 'transformer_weights': None, 'transformers': [('text_tfidf', TfidfVectorizer(max_features=3000), 'text'), ('keyword_tfidf', TfidfVectorizer(max_features=500), 'keyword'), ('location_tfidf', TfidfVectorizer(max_features=500), 'location')], 'verbose': False, 'verbose_feature_names_out': True, 'text_tfidf': TfidfVectorizer(max_features=3000), 'keyword_tfidf': TfidfVectorizer(max_features=500), 'location_tfidf': TfidfVectorizer(max_features=500), 'text_tfidf__analyzer': 'word', 'text_tfidf__binary': False, 'text_tfidf__decode_error': 'strict', 'text_tfidf__dtype': <class 'numpy.float64'>, 'text_tfidf__encoding': 'utf-8', 'text_tfidf__input': 'content', 'text_tfidf__lowercase': True, 'text_tfidf__max_df': 1.0, 'text_tfidf__max_features': 3000, 'text_tfidf__min_df': 1, 'text_tfidf__ngram_range': (1, 1), 'text_tfidf__norm': 'l2', 'text_tfidf__preprocessor': None, 'text_tfidf__smooth_idf': True, 'text_tfidf__stop_words': None, 'text_tfidf__strip_accents': None, 'text_tfidf__sublinear_tf': False, 'text_tfidf__token_pattern': '(?u)\\b\\w\\w+\\b', 'text_tfidf__tokenizer': None, 'text_tfidf__use_idf': True, 'text_tfidf__vocabulary': None, 'keyword_tfidf__analyzer': 'word', 'keyword_tfidf__binary': False, 'keyword_tfidf__decode_error': 'strict', 'keyword_tfidf__dtype': <class 'numpy.float64'>, 'keyword_tfidf__encoding': 'utf-8', 'keyword_tfidf__input': 'content', 'keyword_tfidf__lowercase': True, 'keyword_tfidf__max_df': 1.0, 'keyword_tfidf__max_features': 500, 'keyword_tfidf__min_df': 1, 'keyword_tfidf__ngram_range': (1, 1), 'keyword_tfidf__norm': 'l2', 'keyword_tfidf__preprocessor': None, 'keyword_tfidf__smooth_idf': True, 'keyword_tfidf__stop_words': None, 'keyword_tfidf__strip_accents': None, 'keyword_tfidf__sublinear_tf': False, 'keyword_tfidf__token_pattern': '(?u)\\b\\w\\w+\\b', 'keyword_tfidf__tokenizer': None, 'keyword_tfidf__use_idf': True, 'keyword_tfidf__vocabulary': None, 'location_tfidf__analyzer': 'word', 'location_tfidf__binary': False, 'location_tfidf__decode_error': 'strict', 'location_tfidf__dtype': <class 'numpy.float64'>, 'location_tfidf__encoding': 'utf-8', 'location_tfidf__input': 'content', 'location_tfidf__lowercase': True, 'location_tfidf__max_df': 1.0, 'location_tfidf__max_features': 500, 'location_tfidf__min_df': 1, 'location_tfidf__ngram_range': (1, 1), 'location_tfidf__norm': 'l2', 'location_tfidf__preprocessor': None, 'location_tfidf__smooth_idf': True, 'location_tfidf__stop_words': None, 'location_tfidf__strip_accents': None, 'location_tfidf__sublinear_tf': False, 'location_tfidf__token_pattern': '(?u)\\b\\w\\w+\\b', 'location_tfidf__tokenizer': None, 'location_tfidf__use_idf': True, 'location_tfidf__vocabulary': None}

In [49]:
model = Sequential()
model.add(Dense(128, input_dim=3739, activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.3))
model.add(Dense(64, activation='relu', kernel_regularizer=l2(0.001)))
model.add(BatchNormalization())
model.add(Dropout(0.3))
model.add(Dense(1, activation='sigmoid'))  

model.compile(optimizer=Adam(learning_rate=0.0001), loss='binary_crossentropy', metrics=['accuracy'])

In [51]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 128)                 │         478,720 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ batch_normalization                  │ (None, 128)                 │             512 │
│ (BatchNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout (Dropout)                    │ (None, 128)                 │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 64)                  │           8,256 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ batch_normalization_1                │ (None, 64)                  │             256 │
│ (BatchNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_1 (Dropout)                  │ (None, 64)                  │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 1)                   │              65 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 487,809 (1.86 MB)

 Trainable params: 487,425 (1.86 MB)

 Non-trainable params: 384 (1.50 KB)

In [27]:
from keras.callbacks import EarlyStopping

    monitor='val_loss',         
    patience=7,                
    restore_best_weights=True  
)

IndentationError: unexpected indent (1891083153.py, line 3)

In [28]:
from keras.callbacks import ReduceLROnPlateau

    monitor='val_loss',
    factor=0.5,
    patience=7,
    min_lr=1e-5
)

IndentationError: unexpected indent (202158073.py, line 3)

In [30]:
#model.fit(
    X_train_vec.toarray(),ytr,
    validation_data=(X_val_vec.toarray(), yts),
    epochs=20, batch_size=64,
    callbacks=[early_stop,reduce_lr]
)

IndentationError: unexpected indent (508466017.py, line 2)

In [53]:
model.fit(
    X_train_vec.toarray(),ytr,
    validation_data=(X_val_vec.toarray(), yts),
    epochs=30, batch_size=64,
)

Epoch 1/30
95/95 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - accuracy: 0.5075 - loss: 1.0169 - val_accuracy: 0.5989 - val_loss: 0.7502
Epoch 2/30
95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.6694 - loss: 0.7456 - val_accuracy: 0.5989 - val_loss: 0.7473
Epoch 3/30
95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.7195 - loss: 0.6365 - val_accuracy: 0.5989 - val_loss: 0.7324
Epoch 4/30
95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.7518 - loss: 0.5855 - val_accuracy: 0.6334 - val_loss: 0.6888
Epoch 5/30
95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.7986 - loss: 0.5096 - val_accuracy: 0.7181 - val_loss: 0.6280
Epoch 6/30
95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.8284 - loss: 0.4645 - val_accuracy: 0.7809 - val_loss: 0.5742
Epoch 7/30
95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.8520 - loss: 0.4261 - val_accuracy: 0.7955 - val_loss: 0.5485
Epoch 8/30
95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.8677 - loss: 0.4009 - val_accuracy: 0.7915 - val_loss: 0.5415
Epoch 9/30
95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.8808 - loss: 0.3735 - val_accuracy: 0.7929 - val_loss: 0.5432
Epoch 10/30
95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.8938 - loss: 0.3394 - val_accuracy: 0.7968 - val_loss: 0.5464
Epoch 11/30
95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.9149 - loss: 0.3132 - val_accuracy: 0.7942 - val_loss: 0.5520
Epoch 12/30
95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.9100 - loss: 0.3043 - val_accuracy: 0.7935 - val_loss: 0.5555
Epoch 13/30
95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.9192 - loss: 0.2913 - val_accuracy: 0.7935 - val_loss: 0.5628
Epoch 14/30
95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9362 - loss: 0.2599 - val_accuracy: 0.7882 - val_loss: 0.5699
Epoch 15/30
95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9373 - loss: 0.2495 - val_accuracy: 0.7869 - val_loss: 0.5777
Epoch 16/30
95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9405 - loss: 0.2317 - val_accuracy: 0.7889 - val_loss: 0.5860
Epoch 17/30
95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9523 - loss: 0.2177 - val_accuracy: 0.7929 - val_loss: 0.5945
Epoch 18/30
95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9560 - loss: 0.2089 - val_accuracy: 0.7929 - val_loss: 0.6010
Epoch 19/30
95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9564 - loss: 0.2003 - val_accuracy: 0.7889 - val_loss: 0.6083
Epoch 20/30
95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9609 - loss: 0.1953 - val_accuracy: 0.7862 - val_loss: 0.6167
Epoch 21/30
95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9607 - loss: 0.1881 - val_accuracy: 0.7816 - val_loss: 0.6255
Epoch 22/30
95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9699 - loss: 0.1695 - val_accuracy: 0.7816 - val_loss: 0.6338
Epoch 23/30
95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9694 - loss: 0.1648 - val_accuracy: 0.7849 - val_loss: 0.6457
Epoch 24/30
95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9707 - loss: 0.1717 - val_accuracy: 0.7842 - val_loss: 0.6564
Epoch 25/30
95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.9765 - loss: 0.1470 - val_accuracy: 0.7836 - val_loss: 0.6653
Epoch 26/30
95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9715 - loss: 0.1512 - val_accuracy: 0.7869 - val_loss: 0.6735
Epoch 27/30
95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9726 - loss: 0.1514 - val_accuracy: 0.7836 - val_loss: 0.6806
Epoch 28/30
95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9807 - loss: 0.1338 - val_accuracy: 0.7862 - val_loss: 0.6858
Epoch 29/30
95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9799 - loss: 0.1350 - val_accuracy: 0.7823 - val_loss: 0.6961
Epoch 30/30
95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9771 - loss: 0.1364 - val_accuracy: 0.7862 - val_loss: 0.7033

In [ ]:
import pickle

#with open('tfidf_vectorizer04.pkl', 'wb') as f:
    pickle.dump(tfidf, f)

In [ ]:
#model.save('best_model04_80.h5')

In [ ]:
#from keras.models import load_model
#import pickle

# Load model
#model = load_model('best_model.h5')

# Load vectorizer
#with open('tfidf_vectorizer.pkl', 'rb') as f:
    #tfidf = pickle.load(f)

# Now you can use tfidf.transform(new_text) just like before

In [ ]:
pred = model.predict(X_val_vec)
pred

In [ ]:
pred_class = (pred > 0.5).astype(int).reshape(-1)
pred_class

In [ ]:
yts

In [ ]:
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score

ac=accuracy_score(pred_class,yts)
re=recall_score(pred_class,yts,average='macro') #macro, micro, weighted reason=> study
pr=precision_score(pred_class,yts,average='macro')
f1=f1_score(pred_class,yts,average='macro')

print('Accuracy:',ac)
print('Recall:',re)
print('Precision:',pr)
print('F1 Score:',f1)