In [1]:
from keras.models import load_model
import pickle


model = load_model('best_model03_80.h5')


with open('tfidf_vectorizer03.pkl', 'rb') as f:
    tfidf = pickle.load(f)

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
x=pd.read_csv(r"C:\Users\shubh\Downloads\nlp-getting-started\train.csv")
x

,id,keyword,location,text,target
0,1,NaN,NaN,Our Deeds are the Reason of this #earthquake M...,1
1,4,NaN,NaN,Forest fire near La Ronge Sask. Canada,1
2,5,NaN,NaN,All residents asked to 'shelter in place' are ...,1
3,6,NaN,NaN,"13,000 people receive #wildfires evacuation or...",1
4,7,NaN,NaN,Just got sent this photo from Ruby #Alaska as ...,1
...,...,...,...,...,...
7608,10869,NaN,NaN,Two giant cranes holding a bridge collapse int...,1
7609,10870,NaN,NaN,@aria_ahrary @TheTawniest The out of control w...,1
7610,10871,NaN,NaN,M1.94 [01:04 UTC]?5km S of Volcano Hawaii. htt...,1
7611,10872,NaN,NaN,Police investigating after an e-bike collided ...,1
7612,10873,NaN,NaN,The Latest: More Homes Razed by Northern Calif...,1

In [4]:
x=x.dropna(subset=['keyword'])

In [5]:
x['location'] = x['location'].fillna('unknown')

C:\Users\shubh\AppData\Local\Temp\ipykernel_18820\3034306495.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x['location'] = x['location'].fillna('unknown')

In [6]:
x.drop('id',axis=1,inplace=True)
x

C:\Users\shubh\AppData\Local\Temp\ipykernel_18820\763829685.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x.drop('id',axis=1,inplace=True)

,keyword,location,text,target
31,ablaze,Birmingham,@bbcmtd Wholesale Markets ablaze http://t.co/l...,1
32,ablaze,Est. September 2012 - Bristol,We always try to bring the heavy. #metal #RT h...,0
33,ablaze,AFRICA,#AFRICANBAZE: Breaking news:Nigeria flag set a...,1
34,ablaze,"Philadelphia, PA",Crying out for more! Set me ablaze,0
35,ablaze,"London, UK",On plus side LOOK AT THE SKY LAST NIGHT IT WAS...,0
...,...,...,...,...
7578,wrecked,unknown,@jt_ruff23 @cameronhacker and I wrecked you both,0
7579,wrecked,"Vancouver, Canada",Three days off from work and they've pretty mu...,0
7580,wrecked,London,#FX #forex #trading Cramer: Iger's 3 words tha...,0
7581,wrecked,Lincoln,@engineshed Great atmosphere at the British Li...,0
7582,wrecked,unknown,Cramer: Iger's 3 words that wrecked Disney's s...,0

In [7]:
ip=x.drop('target',axis=1)
ip.head()

,keyword,location,text
31,ablaze,Birmingham,@bbcmtd Wholesale Markets ablaze http://t.co/l...
32,ablaze,Est. September 2012 - Bristol,We always try to bring the heavy. #metal #RT h...
33,ablaze,AFRICA,#AFRICANBAZE: Breaking news:Nigeria flag set a...
34,ablaze,"Philadelphia, PA",Crying out for more! Set me ablaze
35,ablaze,"London, UK",On plus side LOOK AT THE SKY LAST NIGHT IT WAS...

In [8]:
op=x.drop(ip,axis=1)
op.head()

    target
31       1
32       0
33       1
34       0
35       0

In [9]:
from sklearn.model_selection import train_test_split
xtr,xts,ytr,yts=train_test_split(ip,op,test_size=0.2,random_state=13)

In [10]:
X_train_vec = tfidf.fit_transform(xtr)

In [11]:
X_val_vec = tfidf.transform(xts)

In [12]:
pred = model.predict(X_val_vec)
pred

48/48 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

array([[0.09706704],
       [0.1368192 ],
       [0.6744466 ],
       ...,
       [0.02013903],
       [0.997434  ],
       [0.9985007 ]], dtype=float32)

In [13]:
pred_class = (pred > 0.5).astype(int).reshape(-1)
pred_class

array([0, 0, 1, ..., 0, 1, 1])

In [14]:
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score

ac=accuracy_score(pred_class,yts)
re=recall_score(pred_class,yts,average='macro') #macro, micro, weighted reason=> study
pr=precision_score(pred_class,yts,average='macro')
f1=f1_score(pred_class,yts,average='macro')

print('Accuracy:',ac)
print('Recall:',re)
print('Precision:',pr)
print('F1 Score:',f1)

Accuracy: 0.8021178027796162
Recall: 0.7961333947883176
Precision: 0.78819265904491
F1 Score: 0.791432938609713

In [33]:
model.save("best_model04_80_resaved.keras", save_format="keras")  # This saves in newer .keras format

WARNING:absl:The `save_format` argument is deprecated in Keras 3. We recommend removing this argument as it can be inferred from the file path. Received: save_format=keras